#!/usr/bin/env python3
import os
import pysam
import argparse
import pandas as pd

# script to tag BAM generated by STARsolo for downsampling

def prepare_tags(bam, outbam, bcs, threads):
    
    chrs = [i.split('\t')[0] for i in pysam.idxstats(bam).split('\n')[:-1]]
    bcs = pd.read_csv(bcs, header = None)
    pysam.index(bam)
    
    for chr in chrs:
        if chr == '*':
            chrlabel = 'unmapped'
        else:
            chrlabel = chr
        tmp = bam+".tmp."+chrlabel+".bam"
        inp = pysam.AlignmentFile(bam, 'rb', threads = threads)
        out = pysam.AlignmentFile(tmp, 'wb', template = inp, threads = threads)
        
        for read in inp.fetch(chr):
            cell = read.get_tag('CB')
            if cell in bcs[0].values:
                tc = 'True'
            else:
                tc = 'False'
            read.set_tag(tag = 'TC', value = tc, value_type = 'Z')
            if cell == '-':
                cell = 'NA'
            read.set_tag(tag = 'CB', value = cell, value_type = 'Z')
            if read.has_tag('GN'):
                gene = read.get_tag('GN')
            else:
                gene = 'NA'
            read.set_tag(tag = 'GN', value = gene, value_type = 'Z')
            out.write(read)
    inp.close()
    out.close()
        
    bams = [bam+".tmp."+c+".bam" for c in chrs[:-1]]
    bams.append(bam+".tmp."+"unmapped"+".bam")
    cat_args = ['-o', outbam]+bams
    pysam.cat(*cat_args)
    x = [os.remove(b) for b in bams]


def main():
    parser = argparse.ArgumentParser(add_help=True)
    parser.add_argument('--bam', type=str, metavar='FILENAME',
                        help='path to input BAM file')
    parser.add_argument('--out', type=str, metavar='FILENAME',
                        help='path to output bam file')
    parser.add_argument('--bcs', type=str, metavar='FILENAME',
                        help='path to filtered cell barcodes in .csv file')
    parser.add_argument('--n', type=int, default = 4,
                        help='number of threads to use')
    
    args = parser.parse_args()

    prepare_tags(bam = args.bam, outbam = args.out, bcs = args.bcs, threads = args.n)

if __name__ == "__main__":
    main()
